import { ENV } from './env.js';

export const CONFIGTEACHER = {
    DCV_SERVER: ENV.DCV_TEACHER_SERVER,
    DCV_USER: ENV.DCV_TEACHER_USER,
    DCV_PASSWORD: ENV.DCV_TEACHER_PASSWORD
};

export const CONFIGSTUDENT = {
    DCV_SERVER: ENV.DCV_STUDENT_SERVER,
    DCV_USER: ENV.DCV_STUDENT_USER,
    DCV_PASSWORD: ENV.DCV_STUDENT_PASSWORD
};
